# Generated by Django 5.2 on 2025-05-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_title',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='address',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
